host = "localhost"
user = "guest"
password = "guest"
assimilate_file_mq = "assimilate"
memories_exchange = "memories"
memories_routing_key = "created"
database_file_path = ".\\espa.chromadb"
persistent_database = true
collection_name = "memories_collection"