host = "localhost"
user = "guest"
password = "guest"

[[exchanges]]
name = "messages"
type = "topic"
durable = true

[[exchanges]]
name = "interactions"
type = "topic"
durable = true

[[exchanges]]
name = "memories"
type = "topic"
durable = true

[[exchanges]]
name = "files"
type = "topic"
durable = true

[[queues]]
name = "form_interaction"
[[queues.binds]]
exchange_name = "messages"
routing_key = "received"

[[queues]]
name = "assimilate"
[[queues.binds]]
exchange_name = "files"
routing_key = "added"
